build               : "prod/0.1.0/20140824/1/"

title               : "mky.io"
name                : "Micky Hulse"
email               : "m@mky.io"
description         : "Nothing to see here. Move along."
keywords            : ["code", "web development", "design", "art"]

url                 : "http://mky.io/"
uploads             : "http://uploads.mky.io/"
theme               : "http://data.mky.io/"

gwt                 : "hFQuXLW_jYcL7blZAbUFoAVZWMnRZdYKH7hnducJvDE"
bwt                 : "B46559147E88568614EBEBCB2BEF258C"
ga                  : "UA-46485001-1"

highlighter         : "pygments"
relative_permalinks : false
markdown            : "redcarpet"
redcarpet           :
  extensions        : ["smart"]
paginate            : 9999
permalink           : "/:title.html"
timezone            : "America/Los_Angeles"

defaults :
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude             : ["README.md", "Gemfile", "Gemfile.lock"]
include             : ["_pages"]
gems:
  - "jemoji"
  - "jekyll-nada"
