bwt                 : 'B46559147E88568614EBEBCB2BEF258C'
description         : 'A site by me, for me.'
disqus              : 'mhulse'
exclude             : ['CNAME', 'README.md', 'Gemfile', 'Gemfile.lock']
ga                  : 'UA-46485001-1'
gwt                 : 'hFQuXLW_jYcL7blZAbUFoAVZWMnRZdYKH7hnducJvDE'
include             : ['_pages']
markdown            : 'redcarpet'
name                : 'Micky Hulse'
paginate            : 10
paginate_path       : '/page:num/'
permalink           : '/:title/'
pygments            : true
relative_permalinks : false
title               : 'MKY.io'
url                 : 'http://mky.io'
excerpt_separator   : '{{ more }}'
